[build]
  command = "pip install git+https://${GH_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git@8.5.3-insiders-4.24.0 && && pip install --force "mkdocs<1.4" && mkdocs build"
  publish = "site"
