[build]
    command = "npm run build"
    publish = "docs/.vuepress/dist"
# Handle our memory-hungry builds
[build.environment]
  NODE_OPTIONS = "--max_old_space_size=4096"
# link checker whoop! https://github.com/Munter/netlify-plugin-checklinks
[[plugins]]
  package = "netlify-plugin-checklinks"